trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:|
  sudo apt-get install software-properties-common
  sudo apt-add-repository -y ppa:rael-gc/rvm
  sudo apt-get update
  sudo apt-get install rvm
  rvm install ruby
  rvm list
