trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install ruby
    gem install cucumber
    gem install watir
    cucumber --format json
